Feature/network manager
tipe56/StreetCode.com.ua pull request #7
Opened 2024-01-08 13:47 UTC by tipe56

Add network layer, delete MockData, apply placeholder for images, loaderView, Image decoding from base64
Now all data are downloaded from the network.

2024-01-08 20:52 UTC, SerhiiKopytchuk commented on Streetcode.com.ua.xcodeproj/project.pbxproj
> +			);
let's move `RequestProtocol` to another folder `Components/Protocols` and rename `ImageLoader` to `ImageLoaderManager`

2024-01-08 21:30 UTC, SerhiiKopytchuk requested changes

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/ImageLoader.swift
> +}
move this code to another file

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/RequestProtocol.swift
> +public protocol RequestProtocol {
Let's not use Protocol in protocol names. Use Type Instead.
For example: `RequestType`

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/RequestProtocol.swift
> +public extension RequestProtocol {
Same here

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/RequestProtocol.swift
> +        if !urlParameters.isEmpty {
In my opinion there is no need to use this if statement. 
in case its empty .map() will return empty array

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/RequestProtocol.swift
> +            urlRequest.allHTTPHeaderFields = headers
here as welll

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/RequestProtocol.swift
> +        if !urlParameters.isEmpty {
remove if statement

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +//    func parseJSON<T: Decodable>(data: Data) throws -> T
remove comment if unused

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +protocol DataParserProtocol {
`Protocol` to `Type` in naming

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +    }
You can use make like this:
```
func parse<T: Decodable>(data: Data) throws -> T {
        try JSONDecoder().decode(T.self, from: data)
}
```
And it will replace 2 of them

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +    }
you have implemented this functionality in protocol extension already. So there is no need to have this code

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +    func perform<T: DataDecodable>(_ request: RequestProtocol) async -> Result<Array<T>, APIError>
Remove this line. You can use only first to receive T. For example: `perform<[Person]>(RequestType())`

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +    static func parseArray<T: Decodable>(data: Data) throws -> Array<T>
for this as well

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +    }
and here

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +
Move code higher to other files. It's a bad practice to have it in one file

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Model/CatalogImageModel.swift
> +struct CatalogImageModel: Codable, DataDecodable {
It's bad to have `Model` in the end. Remove it

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Model/CatalogImageModel.swift
> +    public init() {}
remove this line

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Model/CatalogPersonModel.swift
> +
remove whitespaces and comments if you don't need them

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Model/CatalogPersonModel.swift
> +}
As for me it's better to write like this:
```
static let mockData = CatalogPersonModel(
    id: 438,
    title: "Роман Рáтушний «Сенека»",
    url: "roman-ratushnyi-seneka",
    alias: "Активіст, журналіст, доброволець",
    imageID: 2136
)
```
But it's up to you

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Model/CatalogPersonModel.swift
> +//}
remove comments if you don't need it

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Model/HistoricalPerson.swift
> +/*struct HistoricalPerson: Identifiable {
remove it If you don't need it

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogRequest.swift
> +    }
move it to enum declaration instead of extension

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogRequest.swift
> +}
move all this code to declaration of enum instead of extension.
there is no need to have one. You can declare computed properties inside enum

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogVM.swift
> +        self.catalog = [CatalogPersonModel]()
you can make it `@Published var catalog: [CatalogPersonModel] = []` and remove this line

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogVM.swift
> +        self.container = container
If you don't use container in this catalog do not store it

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogVM.swift
> +}
move some code to another function because its hard to read

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogView.swift
> +struct CatalogView<VM>: View where VM: CatalogViewModelProtocol {
bad name for ViewModel. Make it ViewModelType. It will be easy to read for other developers. And in future do not use short names like this

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogView.swift
> +    }
we don't need to have this init. Structs have their own built in init

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/CatalogView/CatalogView.swift
I like that you made it generics 👍

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/PersonPreview/PersonPreviewView.swift
remove if you don't use it

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Screens/PersonPreview/PersonPreviewViewModel.swift
> +*/
remove if not used.
+ do not use `swiftlint:disable all`

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Utilities/Extensions/Int + Ext.swift
Don't add whitespaces around +. Use `Int+Extension`
And use full names for extension

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Utilities/Extensions/Int + Ext.swift
> +extension Int: DataDecodable { }
do we need this?

2024-01-08 21:30 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Views/LoadingView.swift
> +}
remove unused comment or add some logic

2024-01-09 13:49 UTC, tipe56 commented on Streetcode.com.ua.xcodeproj/project.pbxproj
> +			);
Done.

2024-01-09 14:05 UTC, tipe56 commented on Streetcode.com.ua/Managers/ImageLoader.swift
> +protocol ImageLoaderable {
Done

2024-01-09 14:05 UTC, tipe56 commented on Streetcode.com.ua/Managers/ImageLoader.swift
> +}
Done

2024-01-09 14:07 UTC, tipe56 commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +//    func parseJSON<T: Decodable>(data: Data) throws -> T
done

2024-01-09 14:07 UTC, tipe56 commented on Streetcode.com.ua/Managers/WebAPIManager.swift
> +protocol DataParserProtocol {
done

2024-01-09 14:11 UTC, tipe56 commented on Streetcode.com.ua/Model/CatalogImageModel.swift
> +struct CatalogImageModel: Codable, DataDecodable {
Done

2024-01-09 14:12 UTC, tipe56 commented on Streetcode.com.ua/Model/CatalogImageModel.swift
> +    public init() {}
done

2024-01-09 14:19 UTC, tipe56 commented on Streetcode.com.ua/Screens/PersonPreview/PersonPreviewViewModel.swift
> +*/
I removed swiftLint temporary because it brings me more inconvenience than benefit.

2024-01-09 14:42 UTC, tipe56 commented on Streetcode.com.ua/Model/CatalogPersonModel.swift
> +//}
done

2024-01-09 15:06 UTC, tipe56 commented on Streetcode.com.ua/Utilities/Extensions/Int + Ext.swift
done

2024-01-09 15:14 UTC, tipe56 commented on Streetcode.com.ua/Managers/RequestProtocol.swift
> +public protocol RequestProtocol {
Already got enum RequestType
```
public enum RequestType: String {
    case GET
    case POST
}
```

Rename to RequestProtocolType

2024-01-09 17:22 UTC, SerhiiKopytchuk commented on Streetcode.com.ua/Managers/ImageLoader.swift
> +                print("failure")
`func handle loadedImageResult(cacheKey: NSString, cacheImage: Image, result: Result< CatalogImageModel, APIError >) { /// code here }`

2024-01-31 15:09 UTC, merged